name: pre-commit-optional

on:
  pull_request:

jobs:
  pre-commit-optional:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run pre-commit
        uses: pre-commit/actions@v2.0.3
        with:
          pre-commit-config: .pre-commit-config-optional.yaml
