name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
        with:
          pre-commit-config: .pre-commit-config.yaml
