name: pre-commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Run pre-commit
        uses: actions/pre-commit@v1
        with:
          pre-commit-config: .pre-commit-config.yaml
